In [1]:
from array import array

In [3]:
arr = array("i",[1,2,3])
type(arr)

array.array

In [4]:
arr*2 #Nao multiplica a matriz

array('i', [1, 2, 3, 1, 2, 3])

In [5]:
!pip install numpy

     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.0 kB ? eta -:--:--
     ------------------------- ------------ 41.0/61.0 kB 393.8 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 461.8 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   -- ------------------------------------- 1.0/15.5 MB 21.1 MB/s eta 0:00:01
   ------ --------------------------------- 2.4/15.5 MB 25.2 MB/s eta 0:00:01
   -------- ------------------------------- 3.3/15.5 MB 23.3 MB/s eta 0:00:01
   --------- ------------------------------ 3.8/15.5 MB 20.3 MB/s eta 0:00:01
   ----------- ---------------------------- 4.4/15.5 MB 18.9 MB/s eta 0:00:01
   ------------- -------------------------- 5.1/15.5 MB 18.0 MB/s eta 0:00:01
   --------------- ------------------------ 5.8/15.5 MB 17.8 MB/s eta 0:00:01
   ----------------- ---------------------- 6.6/15.5 MB 17.6 MB/s eta 0:00:01
 

In [6]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [9]:
matriz = np.array([[1,2],[3,4]])
print(matriz)


[[1 2]
 [3 4]]


In [11]:
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,9]]])
print(tensor)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 9]]]


In [13]:
print(matriz.shape) # mostra a dimensao 
print(tensor.shape)

(2, 2)
(2, 2, 2)


In [16]:
print(tensor.dtype)
print(matriz.dtype)

int32
int32


In [18]:
ones = np.ones((3,3))
print(ones)

zeros = np.zeros((2,3))
print(zeros)
print(type(zeros))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [19]:
aleatorio = np.random.rand(2,3)
print(aleatorio)

[[0.33262784 0.24379088 0.887005  ]
 [0.73994886 0.74592261 0.21673001]]


In [20]:
aleatorio_int = np.random.randint(0,20,size=(3,3))
print(aleatorio_int)

[[ 2 10 15]
 [ 2  5 13]
 [ 1 11  9]]


In [24]:
execicio = np.random.randint(0,100,size=(10))
print(execicio)
print(type(execicio))
print(execicio.dtype)

[22 20 32  3 60 48 80 20 35 19]
<class 'numpy.ndarray'>
int32


In [33]:
ex2 = np.random.rand(5,5)
#print(ex2)
print(f"Min: {ex2.min()}")
print(f"Max: {ex2.max()}")
print(f"Media: {ex2.mean()}")

Min: 0.00639242139554308
Max: 0.9066631828297358
Media: 0.3898210114894707


In [37]:
exe2 = np.random.rand(10)
print(exe2)
exe3 = exe2*10
print(exe3)
exe3.dtype
exe3.astype(int)

[0.29047237 0.08321453 0.02703114 0.4099798  0.28003535 0.61053388
 0.0513856  0.55322946 0.44167474 0.8727195 ]
[2.90472368 0.83214529 0.27031135 4.09979802 2.8003535  6.10533878
 0.51385596 5.53229464 4.41674745 8.72719501]


array([2, 0, 0, 4, 2, 6, 0, 5, 4, 8])

In [ ]:
!pip install scikit-image